### PR TITLE
Feat: get project profile info populated, closes #23

### LINKED ISSUE #23: get profile page for project
- get destrctured information from the project when /projects/:id/profile is entered 
- populate supporters 
- populate donations
- populate comments
- populate reviews

### PR DESCRIPTION
**Pull request by felmez**
- get destrctured information from the project when /projects/:id/profile is entered
- populate supporters
- populate donations
- populate comments
- populate reviews

closes #23

### CODE REVIEW

**Review by yaman3bd — APPROVED** [review]
good job using the populate 👍

**Comment by felmez** [comment]
@halitbatur can we review this and merge asap i think we need these stuff on main

**Review by halitbatur — APPROVED** [review]
This needs to be tested please make sure to create an Issue for that

**Comment by felmez** [comment]
yes testing issue is updated now i will take a look at these soon @halitbatur thanks for reminding

**Pull request merged**
